[package]
name = "kiy4ku/classic"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

license = "MIT"
description = "A tiny class module for Lua. Attempts to stay simple and provide decent performance by avoiding unnecessary over-abstraction."
authors = ["rxi"]

[dependencies]